name: Update ClashX

on:
  schedule:
    - cron: "15 22 * * *"
  workflow_dispatch:
  push:
    paths:
      - user_rule_clashx.txt

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download remote file
        run: |
          curl -o data2.txt -L http://flapiv2.fldylink.com/zvlqjih1t/m4kavp45bdugfskp?clash=1&extend=1

      - uses: petronny/git-config-user@master
        with:
          path: .

      - name: Process user_rule_clashx.txt
        run: |
          head -6 user_rule_clashx.txt > tmp1.txt
          tail -n +7 user_rule_clashx.txt > tmp2.txt

      - name: Merge files
        run: |
          sed -i '/# > 网易云音乐解锁/i\$(cat tmp1.txt)' data2.txt
          sed -i '/proxy-groups:/a\$(cat tmp2.txt)' data2.txt

      # - name: Read local file
      #   id: read-local-file
      #   run: |
      #     data1=$(sed -n '1,6p' user_rule_clashx.txt)
      #     data3=$(sed -n '7,$p' user_rule_clashx.txt)

      # - name: Insert data1 into data2
      #   run: |
      #     sed -i '/# > 网易云音乐解锁/ i\'"$data1" data2.txt
      #     sed -i '/proxy-groups:/ i\'"$data3" data2.txt

      - name: Save modified data2
        run: |
          set -x
          mv data2.txt clashx.yaml
          git add .
          git commit -m "Update ClashX configuration" || exit 0
          git push origin master

